### ISSUE TITLE
[Wii U] Crash Trying Opening

### ISSUE THREAD

**Issue by LucasMerinoC** [vgmoose/hbas#108]
Hello, I have a problem... when I open the store in homebrew it crashes, is there a solution?

**Comment by vgmoose** [comment]
What is your homebrew setup? HBL version, environment, etc?

It could be https://github.com/fortheusers/hb-appstore/issues/98 if Nimble and Tiramisu are installed

**Comment by vgmoose** [comment]
Closing this issue for now, but can re-open if there's more information.
