### ISSUE TITLE
Downloads won't start (Wii U hb app store)

### ISSUE THREAD

**Issue by catod0** [vgmoose/hbas#109]
Tried downloading controller test and download just won't start, and it also seems to happen with every other app.

This also happens w previous versions of hb app store (no surprise though, just saying).

Only tried on wii u as I don't have switch

No idea if it has happened to other users.

**Comment by vgmoose** [comment]
Can you check SD card write lock? Are other apps able to write to the SD?

**Comment by vgmoose** [comment]
I'm closing this issue for now, but can re-open if more info is provided.

The next release of hb-appstore will also have an SD lock check, and should alert you at launch if it's not able to write to the SD card.
