### ISSUE TITLE
Change HB AppStore music (Wii U)

### ISSUE THREAD

**Issue by AlexCherryBlossom** [vgmoose/hbas#117]
I wanted to change the music in the Homebrew Appstore on Wii U so I just took my file, renamed it background.mp3 and replaced the existent file by it. Now when I go into the store It just plays no music (the music icon is also gone). My file was originally an m4a, could that be the problem?

**Comment by vgmoose** [comment]
> My file was originally an m4a, could that be the problem?

Yes, I think so! Try converting the file to an mp3 first, not just renaming it. In some other contexts renaming might be enough if the player also supports m4a, but in hb-appstore's case this won't work.

There are some free conversion websites online (like [this one](https://cloudconvert.com/m4a-to-mp3)), but there are also PC apps such as [iTunes](https://support.apple.com/en-us/108961) (or, Apple Music as it's called now), and the command line program [ffmpeg](https://ffmpeg.org).

**Comment by AlexCherryBlossom** [comment]
Yeah, I converted the file through vlc and it worked 👍🏽

**Comment by vgmoose** [comment]
Awesome, thanks for the update
