### ISSUE TITLE
Homebrew apps arent showing on the wii u channel

### ISSUE THREAD

**Issue by Rosesinhomebrew** [vgmoose/hbas#123]
**Describe the bug**
Basically i just installed some homebrew files and putted them in Sd/wiiu/apps and NUSspli and other apps arent showing

**Platform:**
Wii U, is the console

**To Reproduce**
Well i putted The NUSspli file in the apps folder but nothing happend and the app isnt showing, (its my frist time doing this sorry if its an easy fix)

**Comment by Rosesinhomebrew** [comment]
EDIT DID IT

**Comment by compucat** [comment]
Not relevant to HBAS; closing.
