### ISSUE TITLE
Categories for Apps

### ISSUE THREAD

**Issue by ThomasIO** [vgmoose/hbas#13]
Add categories, a search bar, and obviously, more apps!

**Comment by CreeperMario** [comment]
I like the idea of categories. What would these be? System Tools? Games? Emulators?
I think the search bar is on the to-do list already, and more apps will show up on the store as they are actually developed and released (psst, follow my Tile Game project, and watch its glory when its finished in a few months... or years).

**Comment by ThomasIO** [comment]
Categories ideas -
1. Entertainment
2. Photo / Videos
2. Utilities
3. Hacking
4. Audio
5. Widgets
6. Other

**Comment by ThomasIO** [comment]
Also. Great work on your homebrew apps!

**Comment by ThomasIO** [comment]
I actually already had one downloaded. :P

**Comment by vgmoose** [comment]
Thank you! :smile: 

**Categories**
I like the idea of categories, and I do think it goes hand in hand with Filtering (#1) and ```<category>...</category>``` field in xml (#3).

My problem with the list you've provided is there aren't enough apps to fit in most of them...
- Hacking (system mods): hid-to-vpad, sdcafiine
- Utilities: filezilla, u-paint, (ddd?)
- Games: tic-tac-toe, tile game, etc
- Emulators 

To me, these sound like they could be good ones to start with, and expanded upon later.

**Search**
This is also somewhat related to #1, although it is more specific. This should be possible using the client-only through a [method similar to this](http://vgmoose.com/blog/implementing-a-static-blog-search-clientside-in-js-6629164446/). One issue with either a server- or client-side search though, is the requirement of using a keyboard and processing text input.

**More apps**
Spread the word that the Wii U is ready for homebrew! More apps are always a good thing, but it's kinda outside the scope of this project. ;(

@QuarkTheAwesome has a [guide in progress](https://gbatemp.net/threads/wip-wii-u-development-tutorial.420975/) on how to get started developing for Wii U. With HBL, the process resembles developing on the Wii with HBC.

**Comment by vgmoose** [comment]
I'm changing this issue to be focused on categories, and splitting Search to #16.

**Comment by pwsincd** [comment]
did i solve the categories issue . or do we need to work more on fine tuning them.. ?? the only category i didnt include was a media one ,, as theres currently no real apps to fill it. but i have ammended all current xml's to include the <category>  and the python adds that attribute to the json. so is this issue closed??

**Comment by vgmoose** [comment]
Yep, categories have now been integrated into the app as of https://github.com/vgmoose/hbas/commit/145be9621ce73543a75cc37628eb9de877630235 to reflect the changes on the web.

**Comment by jslay88** [comment]
Did you make sure your switch is connected to the internet?

I have also noticed it 'happening again', to only go to the home screen and realize I had lost my WiFi connection.

Would be best to get a timeout and message for when the app cannot connect, instead of just hanging on progress bar.
