### ISSUE TITLE
Please add an option to mute music permanently

### ISSUE THREAD

**Issue by RodrigoTomeES** [vgmoose/hbas#79]
**Is your feature request related to a problem? Please describe.**
It is very frustrating to get the music at full volume every time I enter to Homebrew App Store

**Describe the solution you'd like**
Remember the choice of volume setting (also change the icon when it is muted)

**Platform:**
Both, why not

**Comment by Masamune3210** [comment]
Wouldnt it be easier to just turn down your console or tv?

**Comment by RodrigoTomeES** [comment]
> Wouldnt it be easier to just turn dow

The volume of the console or tv is not to hight but the music of Homebrew App Store plays very loud.

**Comment by vgmoose** [comment]
Definitely makes sense to save this setting given the mute button is already there.

There's currently no "preferences" system that the appstore itself uses, but there is json parsing ability. (see [rapidjson usage in libget](https://github.com/fortheusers/libget/blob/master/src/Repo.cpp))

**Comment by vgmoose** [comment]
Some relevant areas:

Mute button callback: [AppList.cpp L427](https://github.com/fortheusers/hb-appstore/blob/master/gui/AppList.cpp#L427)
Mute button init: [AppList.cpp L383](https://github.com/fortheusers/hb-appstore/blob/master/gui/AppList.cpp#L383)

The music can be enabled on the PC build with `-DMUSIC` in the Makefile flags. Currently the Switch build does not have music.

**Comment by RodrigoTomeES** [comment]
> Some relevant areas:
> 
> Mute button callback: [AppList.cpp L427](https://github.com/fortheusers/hb-appstore/blob/master/gui/AppList.cpp#L427)
> Mute button init: [AppList.cpp L383](https://github.com/fortheusers/hb-appstore/blob/master/gui/AppList.cpp#L383)
> 
> The music can be enabled on the PC build with `-DMUSIC` in the Makefile flags. Currently the Switch build does not have music.

Hi,

Maybe the music should be removed in Wii U version to have the same functionality to Switch, if this is easiest than add preference settings.

Thanks for your work,

Rodrigo

**Comment by vgmoose** [comment]
Added in https://github.com/fortheusers/hb-appstore/commit/f2cffc1cc864fda5c44e52136abe8fdda7f83162

When toggling the audio, a file `.toggle_sound` is created or deleted, depending on whether or not the current setting is the inverse of the default setting.
