### ISSUE TITLE
Latest wii u master version doesn't exit

### ISSUE THREAD

**Issue by Xpl0itU** [vgmoose/hbas#80]
**Describe the bug**
When building the latest hbas from master for Wii U, you can't exit, it freezes when trying to do so

**Platform:**
Wii U

**To Reproduce**
Build latest -> try to exit

**Comment by vgmoose** [comment]
Should be fixed now, will leave this issue open until the new release is done.

**Comment by vgmoose** [comment]
Fixed in [2.3.1](https://github.com/fortheusers/hb-appstore/releases/tag/v2.3.1)
