### ISSUE TITLE
Wiiubru gives error 403 "forbidden"

### ISSUE THREAD

**Issue by ilinkgamer2** [vgmoose/hbas#82]
When you try to enter the domain of "https://wiiubru.com" via PC or mobile device , it gives an error like the one in the photo. From what I undertand, it was possible to enter the domain at least until January of this year, did something happen?

Additionally, trying to enter in the wii u appstore via the homebrew launcher gives an instant crash (the console crashes before finishing opening the file from the launcher), which forces you to reboot the entire console; but I'm not sure if this one is because there is something badly configured in my sd files.

Btw, the reason why I'm trying to access the appstore is because I'm trying to find the "hbl2hbc" forwarder for the wii u menu (i already have the forwarder in the homebrew launcher), so if anyone reading this still has it, i would be very thankful if you share it with me

![Captura de pantalla (2)](https://user-images.githubusercontent.com/22433796/166225528-f4d4dcd3-37f4-4e7b-ab34-b695110e0d08.png)

**Comment by vgmoose** [comment]
Can you try again? The main repos were down and have been switched over to backup ones now.

HBL2HBC: https://apps.fortheusers.org/wiiu/hbl2hbc
Uptime info on the outage here: http://status.fortheusers.org

Does the app still crash as well? Even when the repos are down it's supposed to show a "Could not connect" screen (if it's the latest hb-appstore release).

**Comment by ilinkgamer2** [comment]
Ok, so now everything works perfectly, the apptore can be accessed without any problems from my pc and wii u. 
Turns out that the problem when trying to open it from the wii u was that there was a file called "hbas.elf" in "sd:/wiiu/apps/appstore/", I don't know what that does or if that file is supposed to be there, but removing it makes everything work flawlesly.

Also, one last thing if you don't mind; I got the name of the forwarder wrong, what i'm looking for is the WiiU2HBC (which let's you go directly fron the Wii U home menu to the vWii homebrew channel), I had it installed on an old wii u, but the only place where I can find info about it nowadays is in "https://gbatemp.net/threads/release-wiiu2hbc-a-hbl2hbc-forwarder-channel.455991/" but even then the link for the dowload is still broken, do you know any other place where I can get it?

Aside for that, everything is now solved and i have even installed a few things on my wii u, so thanks for the help so far ^^

**Comment by vgmoose** [comment]
Ah, for the channel zips you can try from a previous archive here: https://github.com/fortheusers/hbas-backup-wiiu-repo/tree/master/chan_zips

The hbas.elf was from an older update, deleting it is the right move (it should have been cleaned up previously). And thanks for making the issue!
