### ISSUE TITLE
AppStore crashed while installing RetroArch

### ISSUE THREAD

**Issue by greg1984** [vgmoose/hbas#84]
**Describe the bug**
Once the crash happened it prevented me from installing any applications from the AppStore afterwards.

**Platform:**
Wii U

**To Reproduce**
Let the console power off timer expire in 1 hour and install RetroArch on a new console. It will power off when it is the majority of the way through the install process. This was done with the latest version of Tiramisu.

**Comment by vgmoose** [comment]
This is a really annoying issue, but it should be fixed and tracked by #78
