### ISSUE TITLE
hbas.elf freezing my wii-u in the homebrew launcher

### ISSUE THREAD

**Issue by corndoggoiscool** [vgmoose/hbas#85]
Whenever I open the hbas.elf file in the homebrew launcher, it freezes. The hbas.elf file is the same as the HB app store.  I use the wii-u. You can do this by going into the homebrew launcher in the wii-u menu and opening the HB app store.  I have tried multiple times to open it. I have waited for 5 minutes and nothing has happened. 
I apologize if my grammar isn’t the greatest. 

![86A88DC2-C167-4F7D-9BF6-D3F95C70D607](https://user-images.githubusercontent.com/108954334/178057324-9c530e16-9263-47a9-8de1-72f62c8842fc.jpeg)

**Comment by AaronsPersonalCode** [comment]
If you are actually running version 2.1, then you may want to update the app to version 2.2. Not a dev or anything, but the release for 2.2 says it fixes a lot of bugs and crashes from the previous version.

**Comment by vgmoose** [comment]
^ definitely update to  the newer version, hbas.elf is an older homebrew format that may not be compatible with modern setups.

In the past you were able to upgrade hbas.elf -> appstore.rpx via the app itself, but if you can't launch the app, then the best approach is to upgrade manually.

**Comment by corndoggoiscool** [comment]
@vgmoose 
how do i upgrade versions? is there a tutorial for upgrading wii-u homebrews? i have looked it up and no results have shown. thank you in advance.

**Comment by AaronsPersonalCode** [comment]
That all depends on your current setup. I would recommend checking the wiki on installing Tiramisu. 

https://wiiu.hacks.guide/#/

**Comment by AaronsPersonalCode** [comment]
You may be able to get real time help from the discord server if the wiki doesn’t provide enough answers.

**Comment by corndoggoiscool** [comment]
@CrappyCodeWithAaron and @vgmoose thank you both, i will try to reinstall homebrew and all of my cfw. thank you
