### ISSUE TITLE
Custom Background music doesn't work

### ISSUE THREAD

**Issue by danylopez123** [vgmoose/hbas#87]
**Describe the bug**
As the README.md said down, you can have custom musics for the App Store
I did that, searched for an .mp3 file, renambed it as background.mp3 and added it to sd:/wiiu/apps/appstore/background.mp3
And just to be sure, i re-downloaded the appstore to make sure i stay with the latest release version.

**Platform:**
Wii U (EUR/PAL) with the Tiramisu hack method.

**To Reproduce**
1. Search for a mp3 music you want or make your own.
2. Rename it as background.mp3
3. Place it to sd:/wiiu/apps/appstore/
4. Launch the App Store.
5. Music still the same.

**Comment by doritobob269** [comment]
I can confirm I'm having the exact same issue on Wii U (USA/NTSC) with Tiramisu.
Oddly enough I was trying this exact same thing at the same time!

**Comment by vgmoose** [comment]
You are both fast! That part of the readme  was just added and is referring to an upcoming unreleased build, which can be downloaded from CI here: https://github.com/fortheusers/hb-appstore/actions/runs/3009555813 as either a wuhb, rpx, or nro. (If you do run this pre-release version, it will say there's an update available for itself, ignore that).

These changes are going to be released in the next day or two as v2.3, let me know if you do try them and if there are any issues.

**Comment by doritobob269** [comment]
The background music works! Here's video proof.
[https://i.imgur.com/MxIdaCN.mp4](https://i.imgur.com/MxIdaCN.mp4)
Also shown in the video is the app crashing when I pressed the (-) to quit. I'm using the .rpx version, installed in the /wiiu/apps/appstore folder of an existing hb-appstore install, and loaded through homebrew launcher.

**Comment by vgmoose** [comment]
Can you try this build? https://github.com/fortheusers/hb-appstore/actions/runs/3018646768

Thanks for testing, there's three ways to exit the app: home menu -> exit, quit button (touch), pressing minus, and that last one should be fixed now.

**Comment by doritobob269** [comment]
Home button doesn't open the home menu so I can't test for that.
Touching quit button works.
Pressing minus work!
Thanks so much! This is so cool!

**Comment by danylopez123** [comment]
I've tested this using https://github.com/fortheusers/hb-appstore/actions/runs/3022542061
The music works fine now, however, when i try to quit the appstore, it just boots back to the Wii U menu and not the Homebrew screen.

**Comment by vgmoose** [comment]
That is likely the behavior going forwards, as Aroma rolls out. This the mechanism that official Wii U apps use to exit (or that's my understanding).

**Comment by EnforcerRidley** [comment]
On this new version (for the Switch), down on the D-pad doesn't work, though the control stick does work. Quitting the app also goes to a blank screen, having to press home and close the app with X.

**Comment by vgmoose** [comment]
Does the D-pad thing still occur in this build? https://github.com/fortheusers/hb-appstore/actions/runs/3043040002

Currently trying to resolve the exiting issue. It is likely a result of some file handle that was left open.

**Comment by EnforcerRidley** [comment]
The D-pad for the Switch version is working now. I'm seeing no issues. Thank you!

But something I noticed after posting my last comment. Neither the control stick nor the D-pad for the 3DS version are working. Ordinarily, this wouldn't be a problem for the 3DS, however, the top row of apps is also on the upper screen which isn't a touchpad so cannot be selected or is super hard to select (requires Sorting and hoping the app you want on the upper screen is sorted on another row you can get).

I'm assuming that the 3DS version is experimental at this point of time? The 3DS version also doesn't have support for BG music currently?

**Comment by vgmoose** [comment]
Yep, the 3DS is very experimental at this time. I'm going to focus more on it after this latest Switch/Wii U release round.

The main reason the 3DS and Wii builds don't currently support music is that they're using SDL1 instead of SDL2. Not that it's impossible on SDL1, just that the same wrappers/code haven't been implemented in [Chesto](https://github.com/fortheusers/chesto).

**Comment by vgmoose** [comment]
Fixed in [2.3.1](https://github.com/fortheusers/hb-appstore/releases/tag/v2.3.1)
