### ISSUE TITLE
Crashes when exiting from Aroma

### ISSUE THREAD

**Issue by hamsteronpotato** [vgmoose/hbas#88]
**Describe the bug**
The home button is blocked by the AppStore in favour of the minus (-) button. This causes an issue with Aroma as it comes with a plug-in which causing homebrew to be seen on the main menu. This can be confusing for newbie’s.

**Platform:**
Wii U

**To Reproduce**

1. Setup Aroma
2. Launch the AppStore
3. Attempt to exit via minus button

**Comment by vgmoose** [comment]
It no longer happens in the latest builds: https://github.com/fortheusers/hb-appstore/actions/runs/3043040002

Working on getting a 2.3 release out shortly with this fix (and tracking it in #80).
