### ISSUE TITLE
[Wii U / Aroma] freezes on exit

### ISSUE THREAD

**Issue by zekromisblack** [vgmoose/hbas#90]
**Describe the bug**
freezes on exit when you use aroma cfw if you launch it directly from home menu
**Platform:**
Are you using Switch, Wii U, or PC version?
Wii u
**To Reproduce**
Please provide steps to reproduce the behavior, and what the expected behavior is. If applicable, add screenshots to help explain your problem.
launch the hb appstore from the home menu then press the normal exit button

**Comment by vgmoose** [comment]
Can you check if this is resolved in the latest nightly? https://github.com/fortheusers/hb-appstore/actions/runs/3109686277/jobs/5040132419

**Comment by vgmoose** [comment]
Fixed in [2.3.1](https://github.com/fortheusers/hb-appstore/releases/tag/v2.3.1)
