### ISSUE TITLE
crashes when opened on wii u homebrew 2.1 by Dimak

### ISSUE THREAD

**Issue by Drqad** [vgmoose/hbas#97]
crashes when opened on wii u homebrew 2.1 by Dimak (i downloaded it form this github)

**Comment by vgmoose** [comment]
Are you using a Homebrew launcher channel? You should try Homebrew Launcher 1.5 instead: https://github.com/dimok789/homebrew_launcher/releases

**Comment by vgmoose** [comment]
I think the above diagnosis is right, let me know if it fixes the issue. Also make sure you are running the latest RPX build of hb-appstore.

**Comment by tanner02** [comment]
Had the same issue when attempting to launch the AppStore from the Homebrew Launcher. It would cause to freeze up the whole console. Solution above didn't work for me, maybe i did something wrong though. What did work in my case was [updating the tiramisu files](https://github.com/wiiu-env/Tiramisu/releases) (which includes a copy of Homebrew Launcher 1.5 .elf) on my sd card.
