### ISSUE TITLE
Pretendo Support

### ISSUE THREAD

**Issue by Timbo303** [vgmoose/hbas#98]
**Is your feature request related to a problem? Please describe.**
Yes whenever you load the app store with pretendo it gets stuck on a black screen. However if you connect to under nintendo this does work like intended. Pretendo support would be nice to have since it basically revives online support for games. Super Mario Maker 2 works as well you can upload levels to it again under pretendo.

**Describe the solution you'd like**
Just basic pretendo support just to load into the app. The app should work after that.

**Platform:**
Wii U

**Comment by vgmoose** [comment]
To my knowledge this is a Pretendo+Tiramisu issue (https://github.com/PretendoNetwork/Nimble/issues/6), and should work on Inkay+Aroma.

Do other homebrews (eg. [vgedit](https://github.com/vgmoose/vgedit/releases/tag/v2.1)) have this problem? I'm wondering if it has to do with RPX file size.

**Comment by vgmoose** [comment]
Closing this over here (track in the Nimble issue linked above), but will re-open if there is something needed on the hb-appstore side.
